stages:
  - lint
  - build
  - release
  - deploy

variables:
  CONTAINER_RELEASE_IMAGE_CORE: $CI_REGISTRY_IMAGE_CORE:latest
  CONTAINER_RELEASE_IMAGE_CLIENTSIDE: $CI_REGISTRY_IMAGE_CLIENTSIDE:latest


frontend_lint:
  image: node:lts-alpine3.20
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      allow_failure: false
  before_script:
    - cd frontend
  script:
    - npm install
    - npm run lint
    - npx tsc --noEmit
  artifacts:
    paths:
      - frontend/build/

frontend_build:
  image: node:lts-alpine3.20
  stage: build
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      allow_failure: false
  script:
    - cd frontend
    - npm install
    - npx tsc

backend_build:
  image: golang:latest
  stage: build
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      allow_failure: false
  script:
    - cd backend
    - go mod download
    - go build -o app

frontend_release-image:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: release
  before_script:
    - echo "Logging into Docker hub..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  only:
    - staging
  script:
    - IMAGE_TAG=$(echo "$CI_COMMIT_TIMESTAMP" | sed 's/:/-/g' | sed 's/+/-/g')
    - CONTAINER_TEST_IMAGE_CLIENTSIDE="$CI_REGISTRY_IMAGE_CLIENTSIDE:$IMAGE_TAG"
    - cd frontend
    - echo "Building Docker image..."
    - docker build --pull -t "$CONTAINER_TEST_IMAGE_CLIENTSIDE" .
    - docker push $CONTAINER_TEST_IMAGE_CLIENTSIDE
    - docker tag $CONTAINER_TEST_IMAGE_CLIENTSIDE $CONTAINER_RELEASE_IMAGE_CLIENTSIDE
    - echo "Pushing Docker image to Docker hub......"
    - docker push $CONTAINER_RELEASE_IMAGE_CLIENTSIDE

backend_release-image:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: release
  before_script:
    - echo "Logging into Docker hub..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  only:
    - staging
  script:
    - IMAGE_TAG=$(echo "$CI_COMMIT_TIMESTAMP" | sed 's/:/-/g' | sed 's/+/-/g')
    - CONTAINER_TEST_IMAGE_CORE="$CI_REGISTRY_IMAGE_CORE:$IMAGE_TAG"
    - cd backend
    - echo "Building Docker image..."
    - docker build --pull -t $CONTAINER_TEST_IMAGE_CORE .
    - docker push $CONTAINER_TEST_IMAGE_CORE
    - docker tag $CONTAINER_TEST_IMAGE_CORE $CONTAINER_RELEASE_IMAGE_CORE
    - echo "Pushing Docker image to Docker hub......"
    - docker push $CONTAINER_RELEASE_IMAGE_CORE

deploy-qa:
  image: alpine
  stage: deploy
  only:
    - staging
  needs:
    - frontend_release-image
    - backend_release-image
  before_script:
    - apk update
    - apk add --no-cache openssh
  script:
    - IMAGE_TAG=$(echo "$CI_COMMIT_TIMESTAMP" | sed 's/:/-/g' | sed 's/+/-/g')
    - echo "Deploying to qa ..."
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP "IMAGE_TAG=$IMAGE_TAG ./deploy-qa.sh"

deploy-prod:
  image: alpine
  stage: deploy
  only:
    - staging
  when: manual
  before_script:
    - apk update
    - apk add --no-cache openssh
  script:
    - IMAGE_TAG=$(echo "$CI_COMMIT_TIMESTAMP" | sed 's/:/-/g' | sed 's/+/-/g')
    - echo "Deploying to prod ..."
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP "IMAGE_TAG=$IMAGE_TAG ./deploy-prod.sh"