SERVER_HOST: "0.0.0.0"
SERVER_ORIGINS: "http://localhost:5173"
SERVER_PORT: 5000
DB_AUTOMIGRATE: true
DB_HEADLESS: false
DB_HOST: "server1.oupsn.com"
DB_NAME: "interv-dev"
DB_USERNAME: "interv-dev"
DB_PASSWORD: "interv-dev"
DB_PORT: 5433
DB_URL: "postgres://admin:admin@localhost:5432/interv?sslmode=disable"
JWT_SECRET: "korHaiProjectNeePanPaiDaiDeeee"
ENV: "dev"